/*
 *
 * LoginPage constants
 *
 */

export const DEFAULT_ACTION = 'app/LoginPage/DEFAULT_ACTION';

export const GET_AUTH_CONFIG_DETAILS = "app/LoginPage/GET_AUTH_CONFIG_DETAILS";
export const GET_AUTH_CONFIG_DETAILS_SUCCESS = "app/LoginPage/GET_AUTH_CONFIG_DETAILS_SUCCESS";
export const GET_AUTH_CONFIG_DETAILS_FAILURE = "app/LoginPage/GET_AUTH_CONFIG_DETAILS_FAILURE";

export const GET_TOKEN_DETAILS = "app/LoginPage/GET_TOKEN_DETAILS";
export const GET_TOKEN_DETAILS_SUCCESS = "app/LoginPage/GET_TOKEN_DETAILS_SUCCESS";
export const GET_TOKEN_DETAILS_FAILURE = "app/LoginPage/GET_TOKEN_DETAILS_FAILURE";

export const GET_USER_DETAILS = "app/LoginPage/GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESS = "app/LoginPage/GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "app/LoginPage/GET_USER_DETAILS_FAILURE";
